### ISSUE TITLE
Increasing video limit

### ISSUE THREAD

**Issue by omega8fattyacid** [Dannyman3819/Automatic-Youtube-Downloader#31]
I'd like to use this for archival purposes, could the limit on videos be removed or increased much higher at least?

**Comment by dblevin1** [comment]
This project uses the RSS feed from Youtube, Each pull from Youtube only contains 15 videos so this tool is good for keeping your archive up to date. But not necessarily for downloading an entire channel. You could download a entire channel with youtube-dl by giving it the channel ID instead of a video ID.

**Comment by PizzaWaffles** [comment]
This project uses the RSS feed from Youtube, Each pull from Youtube only contains 15 videos so this tool is good for keeping your archive up to date. But not necessarily for downloading an entire channel. You could download a entire channel with youtube-dl by giving it the channel ID instead of a video ID.
